name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('rmarkdown','ggplot2','dplyr','tidyr'))"

      - name: Build reports
        run: |
          mkdir -p public
          Rscript -e "rmarkdown::render('README.md', output_file='public/index.html')"
          Rscript -e "rmarkdown::render('projects/carwash-market-intelligence/report.Rmd', output_dir='public')"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
