name: Build and Deploy Portfolio Pages

on:
  push:
    branches: [ "main" ]  # Rebuild site on pushes to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:4.3.1  # R 4.3.1 with tidyverse, rmarkdown, pandoc, TinyTeX pre-installed
    env:
      R_LIBS_USER: "$HOME/R"             # Set R library path (will be cached)
      R_COMPILE_AND_INSTALL_PACKAGES: "never"  # Use binaries where possible on Linux
      TZ: "UTC"                          # Set timezone if needed for reproducibility
      _R_CHECK_SYSTEM_CLOCK_: "FALSE"    # Prevent potential R timing issues in containers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/R  # Cache the R library directory (packages installed here)
          key: ${{ runner.os }}-R-4.3.1-${{ hashFiles('**/projects/carwash-market-intelligence/analysis.R', '**/projects/carwash-market-intelligence/report.Rmd') }}
          restore-keys: ${{ runner.os }}-R-4.3.1-

      - name: Install R package dependencies
        run: |
          Rscript -e "install.packages(c('rmarkdown', 'ggplot2', 'dplyr', 'tidyr', 'forecast', 'tidytext'), repos='https://cloud.r-project.org')"

      - name: Build R Markdown reports
        run: |
          # Create output directory
          mkdir -p public
          # Render main portfolio README as index.html (landing page)
          Rscript -e "rmarkdown::render('README.md', output_file='index.html', output_dir='public', output_format='html_document')"
          # Render the Carwash Market Intelligence report to HTML (report.html)
          Rscript -e "rmarkdown::render('projects/carwash-market-intelligence/report.Rmd', output_file='report.html', output_dir='public', knit_root_dir='.')"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Auth token provided by GitHub Actions
          publish_branch: gh-pages  # Branch to deploy to
          publish_dir: public      # Directory with static site files to publish
          user_name: GitHub Actions  # Set a dummy committer name for the gh-pages push
          user_email: actions@github.com  # Set a dummy committer email
