name: Build Reports

on:
  push:
    paths:
      - 'projects/**/*.Rmd'
      - 'projects/**/*.R'

jobs:
  build-reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('rmarkdown','ggplot2','dplyr','tidyr'))"
      - name: Render report
        run: |
          mkdir -p reports
          Rscript -e "rmarkdown::render('projects/carwash-market-intelligence/report.Rmd', output_dir='reports')"
      - name: Auto Commit
        uses: ./.github/actions/autocommit
